// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeManagement.Databases;

#nullable disable

namespace RecipeManagement.Databases.Migrations
{
    [DbContext(typeof(RecipesDbContext))]
    [Migration("20261009075301_AddQualification")]
    partial class AddQualification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeManagement.Domain.Qualifications.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("kcr_qualification_id");

                    b.Property<string>("AuthorizedTrainingPersonnel")
                        .HasColumnType("text")
                        .HasColumnName("authorized_training_personnel");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitialTrainingPerformanceThreshold")
                        .HasColumnType("text")
                        .HasColumnName("initial_training_performance_threshold");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MinimumCompetencyVerification")
                        .HasColumnType("text")
                        .HasColumnName("minimum_competency_verification");

                    b.Property<string>("MinimumRecruitmentRequirements")
                        .HasColumnType("text")
                        .HasColumnName("minimum_recruitment_requirements");

                    b.Property<string>("RecruitmentRequirementsVerification")
                        .HasColumnType("text")
                        .HasColumnName("recruitment_requirements_verification");

                    b.Property<string>("RecurrentCheckPerformanceThreshold")
                        .HasColumnType("text")
                        .HasColumnName("recurrent_check_performance_threshold");

                    b.Property<string>("RequiredPerformanceThresholds")
                        .HasColumnType("text")
                        .HasColumnName("required_performance_thresholds");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("kcr_role_id");

                    b.Property<Guid?>("RoleId1")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecificSkillsAndKnowledge")
                        .HasColumnType("text")
                        .HasColumnName("specific_skills_and_knowledge");

                    b.Property<string>("TrainingFramework")
                        .HasColumnType("text")
                        .HasColumnName("training_framework");

                    b.Property<string>("TrainingMode")
                        .HasColumnType("text")
                        .HasColumnName("training_mode");

                    b.Property<string>("TrainingModules")
                        .HasColumnType("text")
                        .HasColumnName("training_modules");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("RoleId1")
                        .IsUnique();

                    b.ToTable("kcr_qualification", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfOrigin")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Directions")
                        .HasColumnType("text");

                    b.Property<string>("ImageLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("RecipeSourceLink")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeManagement.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("kcr_role_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("kcr_role", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Domain.Qualifications.Qualification", b =>
                {
                    b.HasOne("RecipeManagement.Domain.Roles.Role", "Role")
                        .WithOne()
                        .HasForeignKey("RecipeManagement.Domain.Qualifications.Qualification", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeManagement.Domain.Roles.Role", null)
                        .WithOne("Qualification")
                        .HasForeignKey("RecipeManagement.Domain.Qualifications.Qualification", "RoleId1");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RecipeManagement.Domain.Roles.Role", b =>
                {
                    b.Navigation("Qualification");
                });
#pragma warning restore 612, 618
        }
    }
}
